apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "controlplane.fullname" . }}-migrate
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: {{ .Values.jobs.migrate.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.jobs.migrate.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.jobs.migrate.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "controlplane.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/bin/migrate"]
          env:
            - name: MIX_ENV
              value: "prod"
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.envFromSecrets }}
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
